name: Deploy Docker Image

on:
  push:
    branches:
      - main          # Ajusta según tu branch principal
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Construir y subir la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ignortega/eva_mod10:latest
            ignortega/eva_mod10:sha-${{ github.sha }}
