name: Docker Build & Push (Debug)

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: eva_mod10

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker Hub secrets
        run: |
          echo "Username is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "Token is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"        

      - name: Log in to Docker Hub (debug, sin secrets)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # <-- reemplaza por tu usuario real
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # <-- pega tu token directamente

      - name: Extract version from git
        id: vars
        run: |
          VERSION=$(date +'%Y.%m.%d')-${GITHUB_SHA::7}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
