on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master       # Revisa cambios en el repositorio de github
      - name: build and push to docker      # Carga imagen en la VM de github actions
        uses: docker/build-push-action@v1   # Sube la imagen de docker en docker hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}